SELECT user, host FROM mysql.user;
SELECT USER();
SHOW DATABASES;

DROP USER IF EXISTS 'vLPfv8nW3Xo1HS2v';
CREATE USER IF NOT EXISTS 'vLPfv8nW3Xo1HS2v'
IDENTIFIED BY 'FnkQcnL0m0yBNDbLuLRP0qUPY2ib0hg8DBUgAt8JvCW3tdZUxv2GOeKKAgQ';

SHOW GRANTS FOR 'vLPfv8nW3Xo1HS2v';

REVOKE	ALL PRIVILEGES, GRANT OPTION FROM 'vLPfv8nW3Xo1HS2v';

GRANT	SELECT, INSERT, UPDATE, DELETE, EXECUTE, EVENT
ON		`auction-dev`.*
TO		'vLPfv8nW3Xo1HS2v';


